#!/bin/sh

TOGGLE1=~/.config/i3blocks/.toggle-email

if [ ! -e $TOGGLE1 ]; then
    touch $TOGGLE1
    cp ~/.config/i3/config.original ~/.config/i3/config
else
    rm $TOGGLE1
    cp ~/.config/i3/config.muted-email ~/.config/i3/config
fi

i3-msg restart
