#!/bin/sh

while true; do
	# find ~/Pictures/wallpapers/ -type f \( -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' \) -print0 |
	# 	shuf -n1 -z | xargs -0 feh --bg-fill "$@"
	feh --bg-fill --randomize ~/Pictures/wallpapers/* --bg-fill --randomize ~/Pictures/wallpapers/*
	sleep 5m
done
